### ISSUE TITLE
Feature Request: check price of ripple? Xrp

### ISSUE THREAD

**Issue by LEXmono** [LEXmono/q#109]

**Comment by jimmymack1980** [comment]
Ripple crypto currency price

https://coinmarketcap.com/currencies/ripple/

**Comment by LEXmono** [comment]
This is working via AlphaVantage. 

Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 2.61 KiB | 0 bytes/s, done.
Total 5 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/LEXmono/q.git
   2bc45bf..1d478a6  master -> master
