### ISSUE TITLE
Feature Request: !friday should return this gif: <http://i.imgur.com/MXaLbQk.gif>

### ISSUE THREAD

**Issue by LEXmono** [LEXmono/q#34]

**Comment by sdepew** [comment]
!friday should also mention @ everyone #35

**Comment by sdepew** [comment]
!friday should also check the day and /giphy nope on all days which are not Friday

**Comment by aaron-bowman** [comment]
Created the base function - needs to have the Q functionality added. Pull requested.

**Comment by LEXmono** [comment]
@LEXmono LEXmono merged commit d7784b3 into master  6 minutes ago
