### ISSUE TITLE
Feature Request: !movie {moviename} should return a trailer for a movie

### ISSUE THREAD

**Issue by LEXmono** [LEXmono/q#47]

**Comment by sdepew** [comment]
I haven't found a good API specifically for movie trailers yet, but it might be better to just do a general youtube search. Instead of !movie "moviename", it would be !youtube "whatever video you want to look for"


https://developers.google.com/youtube/v3/docs/search/list

**Comment by LEXmono** [comment]
What I did for `!mt` was just return the AMC movie link which has all the info? Would this be sufficient?
